### ISSUE TITLE
Any information?

### ISSUE THREAD

**Issue by MrPeker** [naynco/nayn.summarizer#1]
Do you have any public plans for summarizing the Turkish text? About techniques, methods, etc. to be used. I was quite excited to see such a repository. I would love to follow the progress on the repository and contribute if I can.

**Comment by hmert** [comment]
@MrPeker 🖐 hi, I'll share a detailed document at here.

**Comment by hmert** [comment]
@MrPeker I've added [a wiki pag](https://github.com/naynco/nayn.summarizer/wiki/Wiki-Home)e to the project. Let me know if it is enough for now.
